name: CI

on:
  push:
    branches: [main]

jobs:
  tests:
    name: tests on ${{ matrix.os }} (${{ matrix.arch }}) for ${{ matrix.cp }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        arch: [auto64]
        cp: ["cp312"]
    env:
      PYGLFW_LIBRARY: glfw-3.4.bin.MACOS/lib-universal/libglfw.3.dylib
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: python -m pip install pyopengl glfw pysdl2 pysdl2-dll
      - run: python -m pip install --pre skia-python
      - run: python issue-214-glut.py
      - run: python issue-214-sdl2.py
#      - run: python issue-214-glfw.py
