name: Linux testing

on:
  push:
  # allow manual launch
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python -m pip install --pre skia-python
      - run: python skparagraph-example.py
