name: Windows testing

on:
  push:
  # allow manual launch
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: python -m pip install --pre skia-python
      - run: python skparagraph-example.py
