name: Windows testing

on:
  push:
  # allow manual launch
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          # 3.x is whatever latest.
          python-version: '3.x'
      - run: python -m pip install --pre skia-python
      - run: python -c 'import sys; print(sys.path)'
      - run: python -c 'import site; print(site.getsitepackages())'
      - run: python -c 'import urllib.request; urllib.request.urlretrieve("https://github.com/unicode-org/icu/releases/download/release-75-1/icu4c-75_1-data-bin-l.zip", "icudatal.zip")'
      - run: unzip icudatal.zip
      - run: python -c 'import os, shutil, site; shutil.copy2("icudt75l.dat", os.path.join(site.getsitepackages()[0], "icudtl.dat"))'
      - run: python skparagraph-example.py
